# Site settings
title: Alyssa Marie
header-img: img/home-bg.png
email: alyssa.m.sidebottom@gmail.com
copyright_name: amsidebottom
description: > # this means to ignore newlines until "baseurl:"
  Coding + Teaching + Etc
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: AlyssaMSide
github_username:  amsidebottom
learn_profile: amsidebottom
email_username: alyssa.m.sidebottom@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
